### ISSUE TITLE
`Token`についてリファクタリングする

### ISSUE THREAD

**Issue by kaitokimuraofficial** [kaitokimuraofficial/go_type_inference#24]
# New Feature Issue

## What
**新しく実装したい機能や実現したいこと**

- `TokenLiteral`関数を削除する
- データ構造をもっと簡潔にする

## Why
**実現したい理由、現在抱えている問題**

- `ast.go`内で`TokenLiteral()`を定義しているが、他のファイルでの使用がない

**/冗長なメンバがテストの質を落としている例**
```go
		"nested function abstraction": {
			input: "fun x -> (fun y -> x + y)",
			expected: ast.Statement{
				Expr: ast.FunExpr{
					Token: token.Token{Type: token.FUN, Literal: "fun"},
					Param: ast.Identifier{
						Token: token.Token{Type: token.IDENT, Literal: "x"},
						Value: "x",
					},
					BodyExpr: ast.FunExpr{
						Token: token.Token{Type: token.FUN, Literal: "fun"},
						Param: ast.Identifier{
							Token: token.Token{Type: token.IDENT, Literal: "y"},
							Value: "y",
						},
```

上のコードでの`Token.Literal`の`string`が同じかどうかは、全く本質的ではなく、むしろ構造や型によって等価かどうかは判断されるべきである
- テストをもっと簡潔に書きたい

## TODO
**`What`を達成するためにすべきこと**

- [x] `Token.TokenLiteral`を削除する
- [x] `token.go`をリファクタリングする
- [x] `lexer.go`と`lexer_test.go`に`token.go`の変更の影響を反映させる
- [x] `ast.Expr`の`Token`を消す(`ast.~~`自体が抽象構文木の木構造として型の役割を果たしているので、追加で`token.Token`の情報はいらない)
- [x] `ast.BinOp`の`Operator`を消す(`token.Type`と情報が重複しているから)
- [x] テストの書き方をよくする

## Others
**その他に、特筆しておきたいこと**

- 特になし

## Refs
**このissueに関連するリンクなど**

- https://cs.opensource.google/go/go/+/refs/tags/go1.23.3:src/go/token/token.go
  - 変数名や実装の参考にする
